# Generated by Django 2.1.5 on 2019-08-21 05:50

import cumpa.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=cumpa.utils.upload_location)),
                ('sender_id', models.CharField(max_length=255)),
                ('logged', models.BooleanField(default=False)),
                ('bot_service', models.BooleanField(default=True)),
                ('balance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
