# Generated by Django 2.1.5 on 2019-08-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('picture', models.CharField(max_length=250)),
                ('sender_id', models.CharField(max_length=250)),
                ('bot_service', models.BooleanField(default=False)),
            ],
        ),
    ]
